# Generated by Django 5.0.3 on 2024-04-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONOR', 'Donor'), ('CLOTHBANKADMIN', 'Clothbankadmin')], max_length=20),
        ),
    ]
