# Generated by Django 5.0.3 on 2024-05-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_destination_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
