# Generated by Django 5.0.3 on 2024-05-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_token',
        ),
    ]
