# Generated by Django 5.0.3 on 2024-05-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_delete_otptoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_duration', models.CharField(max_length=100)),
                ('max_altitude', models.CharField(blank=True, max_length=50)),
                ('trip_type', models.CharField(blank=True, max_length=255)),
                ('transport', models.CharField(blank=True, max_length=255)),
                ('cost', models.CharField(max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.destination')),
            ],
        ),
    ]
