# Generated by Django 5.0.3 on 2024-05-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='destination',
            new_name='destination_name',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='destination_name',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='destination',
            new_name='destination_name',
        ),
    ]
