# Generated by Django 5.0.3 on 2024-05-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
