# Generated by Django 5.0.3 on 2024-05-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
