# Generated by Django 5.0.6 on 2024-05-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_rename_destination_name_destination_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.trip'),
            preserve_default=False,
        ),
    ]
