# Generated by Django 5.0.3 on 2024-03-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confrim_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
