# Generated by Django 5.0.3 on 2024-03-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confrim_password',
            new_name='confirm_password',
        ),
    ]
