# Generated by Django 5.0.3 on 2024-05-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_created_at_feedback_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
